config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'notes#index', as: :tag
  get '/:name', to: 'notes#index', as: :name
  resources :notes
  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :user, presence:true
    belongs_to :user, optional: true
    acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    if params[:name]
      Note.where(['name LIKE ?', "%#{params[:name]}%"])
    else
      Note.all
    end
    @tags = Note.tag_counts_on(:tags)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new

  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(
    note_params.merge( user_id: session[:id])
    )
    @note.user = current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to root_path, notice: 'ノートが作成されました' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to root_path, notice: 'ノートが更新されました' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :birthday, :where_from, :hobby, :detail, :image, :tag_list, :image_cache, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profilenote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--jquery-->
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
    
    <!--fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!--lightbox-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>
    
    <!--mateerial icon-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <% require "date" %>

  </head>
  <body
    <header>
      <nav class="grey darken">
        <div class="nav-wrapper">
          <% if user_signed_in? %>
            <%= link_to edit_user_registration_path, :method => :get do %>
              <i class="fas fa-edit"></i><%=current_user.username%>
            <% end %>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
            <%= link_to root_path, :method => :get do %>
              <h2 class="brand-logo center">ProfileNote</h>
            <% end %>
          <% else %>
            <%= link_to new_user_registration_path, :method => :get do %>
              <i class="fas fa-user-plus"></i>サインアップ
            <% end %>
            <%= link_to new_user_session_path, :method => :get do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
            <%= link_to root_path, :method => :get do %>
              <h2 class="brand-logo center">ProfileNote</h>
            <% end %>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
              <div class="new_note">
                <%= link_to new_note_path, method: :get do %>
                  <div class="waves-effect waves-dark btn right">新規プロフィール</div>
                <% end %>
              </div>
              <%= yield %>
            </div>
        </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "名前" %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field image">
    <%= form.label '人物写真' %>

      <div id="img_field" onClick="$('#file').click()" >

        <% if @note.image.url.present? %>
          <%= image_tag(@note.image.url) %>
        <% else %>
          <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
        <% end %>
  
      </div>
    
    <%= form.file_field :image, class: "image", style: "display:none;", id: "file"%>
  </div>

  
  <div class="field">
    <%= form.label "タグ（カンマでつなぐことで複数入力できます）" %>
    <%= form.text_field :tag_list, value: @note.tag_list.join(','), class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label "誕生日（yyyymmddで入力してください）" %>
    <%= form.number_field :birthday %>
  </div>

  <div class="field">
    <%= form.label "出身" %>
    <%= form.text_field :where_from %>
  </div>

  <div class="field">
    <%= form.label "趣味" %>
    <%= form.text_area :hobby %>
  </div>

  <div class="field">
    <%= form.label "詳細" %>
    <%= form.text_area :detail %>
  </div>

  <%= button_tag class: 'btn waves-effect waves-light' do %>
    <%= content_tag :i, "send", class: "material-icons right" %>登録
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div id="tag_cloud">
  使用タグ一覧:<% tag_cloud current_user.notes.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
  <% if params[:tag] %>
    <% current_user.notes.tagged_with("#{params[:tag]}").each do |note| %>
      <div class="card col s6 m4 l4">
        <div class="card-image waves-effect waves-block waves-light">
          <%=  link_to note.image.to_s, 'data-lightbox': note.image.to_s do %>
            <%= image_tag note.image.to_s, height: '250', :style=>"width:300;" %>
          <% end %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= note.name %><i class="material-icons right">more_vert</i></span>
          <%= link_to '編集', edit_note_path(note) %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= note.name %><i class="material-icons right">close</i></span>
          <p><%= raw note.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
          <p class="birthday">
            <%= (Date.today.strftime("%Y%m%d").to_i - note.birthday.to_i) / 10000 %>歳
            <%= note.birthday %>生まれ
          </p>
          <p><%= note.where_from %>出身</p>
          <p>趣味:<%= note.hobby %></p>
          <p>備考:<%= note.detail %></p>
        </div>
        <%= link_to '削除', note, method: :delete, data: { confirm: '本当に削除しますか?' } %>
      </div>
    <% end %>
  <% else %>
    <% current_user.notes.each do |note| %>
      <div class="card col s3 m4 l8">
        <div class="card-image waves-effect waves-block waves-light">
          <%=  link_to note.image.to_s, 'data-lightbox': note.image.to_s do %>
            <%= image_tag note.image.to_s, height: '250', :style=>"width:300;" %>
          <% end %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= note.name %><i class="material-icons right">more_vert</i></span>
          <%= link_to '編集', edit_note_path(note) %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= note.name %><i class="material-icons right">close</i></span>
          <p><%= raw note.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
          <p class="birthday">
            <%= (Date.today.strftime("%Y%m%d").to_i - note.birthday.to_i) / 10000 %>歳
            <%= note.birthday %>生まれ
          </p>
          <p><%= note.where_from %>出身</p>
          <p>趣味:<%= note.hobby %></p>
          <p>備考:<%= note.detail %></p>
        </div>
        <%= link_to '削除', note, method: :delete, data: { confirm: '本当に削除しますか?' } %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/notes/new.html.erb
<h1>新規プロフィール</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @note.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @note.birthday %>
</p>

<p>
  <strong>Where from:</strong>
  <%= @note.where_from %>
</p>

<p>
  <strong>Hobby:</strong>
  <%= @note.hobby %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @note.detail %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>